@CQRS.Sample_HostAddress = http://localhost:5000

POST {{CQRS.Sample_HostAddress}}/api/orders/
Accept: application/json

{
  "customerName": "Thinh",
  "items": [
    {
      "orderId": "123e4567-e89b-12d3-a456-426614174000",
      "productId": "223e4567-e89b-12d3-a456-426614174001",
      "productName": "Cup",
      "quantity": 2,
      "price": 1.5
    }
  ]
}

###

GET {{CQRS.Sample_HostAddress}}/api/orders/de770d1e-b815-4a20-82ba-da291e59d5aa
Accept: application/json

###