@CQRS.Sample_HostAddress = http://localhost:5000

POST {{CQRS.Sample_HostAddress}}/api/orders/
Content-Type: application/json
Accept: application/json

{
  "customerName": "Thinh",
  "items": [
    {
      "productId": "223e4567-e89b-12d3-a456-426614174001",
      "productName": "Cup",
      "quantity": 5,
      "price": 1.5
    },
    {
      "productId": "223e4567-e89b-12d3-a456-426614174022",
      "productName": "Bow",
      "quantity": 10,
      "price": 2.5
    }
  ]
}

###

GET {{CQRS.Sample_HostAddress}}/api/orders/de770d1e-b815-4a20-82ba-da291e59d5aa
Accept: application/json

###